# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='frame',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pins_hit',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='score',
            field=models.SmallIntegerField(),
        ),
    ]
