# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0003_auto_20160124_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='player',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='GameScore',
        ),
    ]
